# Colors (Retro theme)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#000000'
# soft contrast background = = '#32302f'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff3100'
green   = '#6bce39'
yellow  = '#ffce00'
blue    = '#009cff'
magenta = '#3030cf'
cyan    = '#008080'
white   = '#ffffff'

# Bright colors
#[colors.bright]
#black   = '#928374'
#red     = '#fb4934'
#green   = '#b8bb26'
#yellow  = '#fabd2f'
#blue    = '#83a598'
#magenta = '#d3869b'
#cyan    = '#8ec07c'
#white   = '#ebdbb2'

